export let departmentsData = [
    { "numero": "01", "nom": "Ain", "region": "Auvergne-Rhône-Alpes", "legende": "Préfecture : Bourg-en-Bresse", "deploiement": 0, "concerné": false },
    { "numero": "02", "nom": "Aisne", "region": "Hauts-de-France", "legende": "Préfecture : Laon", "deploiement": 0, "concerné": false },
    { "numero": "03", "nom": "Allier", "region": "Auvergne-Rhône-Alpes", "legende": "Préfecture : Moulins", "deploiement": 0, "concerné": false },
    { "numero": "04", "nom": "Alpes-de-Haute-Provence", "region": "Provence-Alpes-Côte d'Azur", "legende": "Préfecture : Digne-les-Bains", "deploiement": 0, "concerné": false },
    { "numero": "05", "nom": "Hautes-Alpes", "region": "Provence-Alpes-Côte d'Azur", "legende": "Préfecture : Gap", "deploiement": 0, "concerné": false },
    { "numero": "06", "nom": "Alpes-Maritimes", "region": "Provence-Alpes-Côte d'Azur", "legende": "Département de Nice", "deploiement": 0, "concerné": false },
    { "numero": "07", "nom": "Ardèche", "region": "Auvergne-Rhône-Alpes", "legende": "Préfecture : Privas", "deploiement": 0, "concerné": false },
    { "numero": "08", "nom": "Ardennes", "region": "Grand Est", "legende": "Préfecture : Charleville-Mézières", "deploiement": 0, "concerné": false },
    { "numero": "09", "nom": "Ariège", "region": "Occitanie", "legende": "Préfecture : Foix", "deploiement": 0, "concerné": false },
    { "numero": "10", "nom": "Aube", "region": "Grand Est", "legende": "Préfecture : Troyes", "deploiement": 0, "concerné": false },
    { "numero": "11", "nom": "Aude", "region": "Occitanie", "legende": "Préfecture : Carcassonne", "deploiement": 0, "concerné": false },
    { "numero": "12", "nom": "Aveyron", "region": "Occitanie", "legende": "Préfecture : Rodez", "deploiement": 0, "concerné": false },
    { "numero": "13", "nom": "Bouches-du-Rhône", "region": "Provence-Alpes-Côte d'Azur", "legende": "Département de Marseille", "deploiement": 0, "concerné": false },
    { "numero": "14", "nom": "Calvados", "region": "Normandie", "legende": "Préfecture : Caen", "deploiement": 0, "concerné": false },
    { "numero": "15", "nom": "Cantal", "region": "Auvergne-Rhône-Alpes", "legende": "Préfecture : Aurillac", "deploiement": 0, "concerné": false },
    { "numero": "16", "nom": "Charente", "region": "Nouvelle-Aquitaine", "legende": "Préfecture : Angoulême", "deploiement": 0, "concerné": false },
    { "numero": "17", "nom": "Charente-Maritime", "region": "Nouvelle-Aquitaine", "legende": "Préfecture : La Rochelle", "deploiement": 0, "concerné": false },
    { "numero": "18", "nom": "Cher", "region": "Centre-Val de Loire", "legende": "Préfecture : Bourges", "deploiement": 0, "concerné": false },
    { "numero": "19", "nom": "Corrèze", "region": "Nouvelle-Aquitaine", "legende": "Préfecture : Tulle", "deploiement": 0, "concerné": false },
    { "numero": "21", "nom": "Côte-d'Or", "region": "Bourgogne-Franche-Comté", "legende": "Préfecture : Dijon", "deploiement": 0, "concerné": false },
    { "numero": "22", "nom": "Côtes-d'Armor", "region": "Bretagne", "legende": "Préfecture : Saint-Brieuc", "deploiement": 0, "concerné": false },
    { "numero": "23", "nom": "Creuse", "region": "Nouvelle-Aquitaine", "legende": "Préfecture : Guéret", "deploiement": 0, "concerné": false },
    { "numero": "24", "nom": "Dordogne", "region": "Nouvelle-Aquitaine", "legende": "Préfecture : Périgueux", "deploiement": 0, "concerné": false },
    { "numero": "25", "nom": "Doubs", "region": "Bourgogne-Franche-Comté", "legende": "Préfecture : Besançon", "deploiement": 0, "concerné": false },
    { "numero": "26", "nom": "Drôme", "region": "Auvergne-Rhône-Alpes", "legende": "Préfecture : Valence", "deploiement": 0, "concerné": false },
    { "numero": "27", "nom": "Eure", "region": "Normandie", "legende": "Préfecture : Évreux", "deploiement": 0, "concerné": false },
    { "numero": "28", "nom": "Eure-et-Loir", "region": "Centre-Val de Loire", "legende": "Préfecture : Chartres", "deploiement": 0, "concerné": false },
    { "numero": "29", "nom": "Finistère", "region": "Bretagne", "legende": "Préfecture : Quimper", "deploiement": 0, "concerné": false },
    { "numero": "30", "nom": "Gard", "region": "Occitanie", "legende": "Préfecture : Nîmes", "deploiement": 0, "concerné": false },
    { "numero": "31", "nom": "Haute-Garonne", "region": "Occitanie", "legende": "Préfecture : Toulouse", "deploiement": 0, "concerné": false },
    { "numero": "32", "nom": "Gers", "region": "Occitanie", "legende": "Préfecture : Auch", "deploiement": 0, "concerné": false },
    { "numero": "33", "nom": "Gironde", "region": "Nouvelle-Aquitaine", "legende": "Département de Bordeaux", "deploiement": 0, "concerné": false },
    { "numero": "34", "nom": "Hérault", "region": "Occitanie", "legende": "Préfecture : Montpellier", "deploiement": 0, "concerné": false },
    { "numero": "35", "nom": "Ille-et-Vilaine", "region": "Bretagne", "legende": "Préfecture : Rennes", "deploiement": 0, "concerné": false },
    { "numero": "36", "nom": "Indre", "region": "Centre-Val de Loire", "legende": "Préfecture : Châteauroux", "deploiement": 0, "concerné": false },
    { "numero": "37", "nom": "Indre-et-Loire", "region": "Centre-Val de Loire", "legende": "Préfecture : Tours", "deploiement": 0, "concerné": false },
    { "numero": "38", "nom": "Isère", "region": "Auvergne-Rhône-Alpes", "legende": "Préfecture : Grenoble", "deploiement": 0, "concerné": false },
    { "numero": "39", "nom": "Jura", "region": "Bourgogne-Franche-Comté", "legende": "Préfecture : Lons-le-Saunier", "deploiement": 0, "concerné": false },
    { "numero": "40", "nom": "Landes", "region": "Nouvelle-Aquitaine", "legende": "Préfecture : Mont-de-Marsan", "deploiement": 0, "concerné": false },
    { "numero": "41", "nom": "Loir-et-Cher", "region": "Centre-Val de Loire", "legende": "Préfecture : Blois", "deploiement": 0, "concerné": false },
    { "numero": "42", "nom": "Loire", "region": "Auvergne-Rhône-Alpes", "legende": "Préfecture : Saint-Étienne", "deploiement": 0, "concerné": false },
    { "numero": "43", "nom": "Haute-Loire", "region": "Auvergne-Rhône-Alpes", "legende": "Préfecture : Le Puy-en-Velay", "deploiement": 0, "concerné": false },
    { "numero": "44", "nom": "Loire-Atlantique", "region": "Pays de la Loire", "legende": "Préfecture : Nantes", "deploiement": 0, "concerné": false },
    { "numero": "45", "nom": "Loiret", "region": "Centre-Val de Loire", "legende": "Préfecture : Orléans", "deploiement": 0, "concerné": false },
    { "numero": "46", "nom": "Lot", "region": "Occitanie", "legende": "Préfecture : Cahors", "deploiement": 0, "concerné": false },
    { "numero": "47", "nom": "Lot-et-Garonne", "region": "Nouvelle-Aquitaine", "legende": "Préfecture : Agen", "deploiement": 0, "concerné": false },
    { "numero": "48", "nom": "Lozère", "region": "Occitanie", "legende": "Préfecture : Mende", "deploiement": 0, "concerné": false },
    { "numero": "49", "nom": "Maine-et-Loire", "region": "Pays de la Loire", "legende": "Préfecture : Angers", "deploiement": 0, "concerné": false },
    { "numero": "50", "nom": "Manche", "region": "Normandie", "legende": "Préfecture : Saint-Lô", "deploiement": 0, "concerné": false },
    { "numero": "51", "nom": "Marne", "region": "Grand Est", "legende": "Préfecture : Châlons-en-Champagne", "deploiement": 0, "concerné": false },
    { "numero": "52", "nom": "Haute-Marne", "region": "Grand Est", "legende": "Préfecture : Chaumont", "deploiement": 0, "concerné": false },
    { "numero": "53", "nom": "Mayenne", "region": "Pays de la Loire", "legende": "Préfecture : Laval", "deploiement": 0, "concerné": false },
    { "numero": "54", "nom": "Meurthe-et-Moselle", "region": "Grand Est", "legende": "Préfecture : Nancy", "deploiement": 0, "concerné": false },
    { "numero": "55", "nom": "Meuse", "region": "Grand Est", "legende": "Préfecture : Bar-le-Duc", "deploiement": 0, "concerné": false },
    { "numero": "56", "nom": "Morbihan", "region": "Bretagne", "legende": "Préfecture : Vannes", "deploiement": 0, "concerné": false },
    { "numero": "57", "nom": "Moselle", "region": "Grand Est", "legende": "Préfecture : Metz", "deploiement": 0, "concerné": false },
    { "numero": "58", "nom": "Nièvre", "region": "Bourgogne-Franche-Comté", "legende": "Préfecture : Nevers", "deploiement": 0, "concerné": false },
    { "numero": "59", "nom": "Nord", "region": "Hauts-de-France", "legende": "Département de Lille", "deploiement": 0, "concerné": false },
    { "numero": "60", "nom": "Oise", "region": "Hauts-de-France", "legende": "Préfecture : Beauvais", "deploiement": 0, "concerné": false },
    { "numero": "61", "nom": "Orne", "region": "Normandie", "legende": "Préfecture : Alençon", "deploiement": 0, "concerné": false },
    { "numero": "62", "nom": "Pas-de-Calais", "region": "Hauts-de-France", "legende": "Préfecture : Arras", "deploiement": 0, "concerné": false },
    { "numero": "63", "nom": "Puy-de-Dôme", "region": "Auvergne-Rhône-Alpes", "legende": "Préfecture : Clermont-Ferrand", "deploiement": 0, "concerné": false },
    { "numero": "64", "nom": "Pyrénées-Atlantiques", "region": "Nouvelle-Aquitaine", "legende": "Préfecture : Pau", "deploiement": 0, "concerné": false },
    { "numero": "65", "nom": "Hautes-Pyrénées", "region": "Occitanie", "legende": "Préfecture : Tarbes", "deploiement": 0, "concerné": false },
    { "numero": "66", "nom": "Pyrénées-Orientales", "region": "Occitanie", "legende": "Préfecture : Perpignan", "deploiement": 0, "concerné": false },
    { "numero": "67", "nom": "Bas-Rhin", "region": "Grand Est", "legende": "Préfecture : Strasbourg", "deploiement": 0, "concerné": false },
    { "numero": "68", "nom": "Haut-Rhin", "region": "Grand Est", "legende": "Préfecture : Colmar", "deploiement": 0, "concerné": false },
    { "numero": "69", "nom": "Rhône", "region": "Auvergne-Rhône-Alpes", "legende": "Département de Lyon", "deploiement": 0, "concerné": false },
    { "numero": "70", "nom": "Haute-Saône", "region": "Bourgogne-Franche-Comté", "legende": "Préfecture : Vesoul", "deploiement": 0, "concerné": false },
    { "numero": "71", "nom": "Saône-et-Loire", "region": "Bourgogne-Franche-Comté", "legende": "Préfecture : Mâcon", "deploiement": 0, "concerné": false },
    { "numero": "72", "nom": "Sarthe", "region": "Pays de la Loire", "legende": "Préfecture : Le Mans", "deploiement": 0, "concerné": false },
    { "numero": "73", "nom": "Savoie", "region": "Auvergne-Rhône-Alpes", "legende": "Préfecture : Chambéry", "deploiement": 0, "concerné": false },
    { "numero": "74", "nom": "Haute-Savoie", "region": "Auvergne-Rhône-Alpes", "legende": "Préfecture : Annecy", "deploiement": 0, "concerné": false },
    { "numero": "75", "nom": "Paris", "region": "Île-de-France", "legende": "Capitale de la France", "deploiement": 0, "concerné": false },
    { "numero": "76", "nom": "Seine-Maritime", "region": "Normandie", "legende": "Préfecture : Rouen", "deploiement": 0, "concerné": false },
    { "numero": "77", "nom": "Seine-et-Marne", "region": "Île-de-France", "legende": "Préfecture : Melun", "deploiement": 0, "concerné": false },
    { "numero": "78", "nom": "Yvelines", "region": "Île-de-France", "legende": "Préfecture : Versailles", "deploiement": 0, "concerné": false },
    { "numero": "79", "nom": "Deux-Sèvres", "region": "Nouvelle-Aquitaine", "legende": "Préfecture : Niort", "deploiement": 0, "concerné": false },
    { "numero": "80", "nom": "Somme", "region": "Hauts-de-France", "legende": "Préfecture : Amiens", "deploiement": 0, "concerné": false },
    { "numero": "81", "nom": "Tarn", "region": "Occitanie", "legende": "Préfecture : Albi", "deploiement": 0, "concerné": false },
    { "numero": "82", "nom": "Tarn-et-Garonne", "region": "Occitanie", "legende": "Préfecture : Montauban", "deploiement": 0, "concerné": false },
    { "numero": "83", "nom": "Var", "region": "Provence-Alpes-Côte d'Azur", "legende": "Préfecture : Toulon", "deploiement": 0, "concerné": false },
    { "numero": "84", "nom": "Vaucluse", "region": "Provence-Alpes-Côte d'Azur", "legende": "Préfecture : Avignon", "deploiement": 0, "concerné": false },
    { "numero": "85", "nom": "Vendée", "region": "Pays de la Loire", "legende": "Préfecture : La Roche-sur-Yon", "deploiement": 0, "concerné": false },
    { "numero": "86", "nom": "Vienne", "region": "Nouvelle-Aquitaine", "legende": "Préfecture : Poitiers", "deploiement": 0, "concerné": false },
    { "numero": "87", "nom": "Haute-Vienne", "region": "Nouvelle-Aquitaine", "legende": "Préfecture : Limoges", "deploiement": 0, "concerné": false },
    { "numero": "88", "nom": "Vosges", "region": "Grand Est", "legende": "Préfecture : Épinal", "deploiement": 0, "concerné": false },
    { "numero": "89", "nom": "Yonne", "region": "Bourgogne-Franche-Comté", "legende": "Préfecture : Auxerre", "deploiement": 0, "concerné": false },
    { "numero": "90", "nom": "Territoire de Belfort", "region": "Bourgogne-Franche-Comté", "legende": "Préfecture : Belfort", "deploiement": 0, "concerné": false },
    { "numero": "91", "nom": "Essonne", "region": "Île-de-France", "legende": "Préfecture : Évry", "deploiement": 0, "concerné": false },
    { "numero": "92", "nom": "Hauts-de-Seine", "region": "Île-de-France", "legende": "Préfecture : Nanterre", "deploiement": 0, "concerné": false },
    { "numero": "93", "nom": "Seine-Saint-Denis", "region": "Île-de-France", "legende": "Préfecture : Bobigny", "deploiement": 0, "concerné": false },
    { "numero": "94", "nom": "Val-de-Marne", "region": "Île-de-France", "legende": "Préfecture : Créteil", "deploiement": 0, "concerné": false },
    { "numero": "95", "nom": "Val-d'Oise", "region": "Île-de-France", "legende": "Préfecture : Cergy", "deploiement": 0, "concerné": false },
    { "numero": "2A", "nom": "Corse-du-Sud", "region": "Corse", "legende": "Préfecture : Ajaccio", "deploiement": 0, "concerné": false },
    { "numero": "2B", "nom": "Haute-Corse", "region": "Corse", "legende": "Préfecture : Bastia", "deploiement": 0, "concerné": false }
]
;

// Charger les données depuis le localStorage
export function loadDepartmentsData() {
    const savedData = JSON.parse(localStorage.getItem('departmentsData'));
    if (savedData) {
        departmentsData = savedData;
    }
}

// data.js
export function saveDepartmentsData() {
    localStorage.setItem('departmentsData', JSON.stringify(departmentsData));
}
